### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by magiruuvelvet** [magiruuvelvet/OTPGen2#1]
Tracking tasks which are to do.

**Core**
- [x] OTP generator
- [x] serialization/deserialization to save/restore
- [x] QR code decoder
- [x] QR code encoder
- [x] token store (encrypt, decrypt)
- [ ] support to change order of tokens in the token store
- [ ] app support for import (refactor code from version 1 for this)
- [ ] export feature

**GUI**
- [ ] import/export dialog
- [ ] mobile and touch-friendly interface for Linux-based Smartphones (PinePhone, etc.)
- [ ] support to change order of tokens rather than force order of insertion
